### ISSUE TITLE
Still unable to claim pending rewards

### ISSUE THREAD

**Issue by misel86** [ATOR-Development/ator-dashboard#120]
Hello, after closing #98, I'm still unable to claim rewards. When the other issue was closed I was able to hit the claim button again (I suppose something was stuck in the backend which was removed/resolved, but immediately after that I got the same issue (see my last comment in #98. Address is 0xacF8A386FD79f71379759515024Bd2ce3072B30b

The new dashboard GUI is now showing the following:

![image](https://github.com/ATOR-Development/ator-dashboard/assets/5527854/387d431b-8ec0-40fe-9bc2-e8a95147f6cf)

**Comment by jim-toth** [comment]
This is the expected UI when you have a pending claim.  We'll investigate why the claim is taking so long.

**Comment by kanshi** [comment]
Should be fixed now. Please review and reopen if necessary.
