### ISSUE TITLE
My pending rewards are accruing but relays disappeared

### ISSUE THREAD

**Issue by ercbul** [ATOR-Development/ator-dashboard#121]
**Description**
I can see My Pending rewards total increasing but none of my claimed relays show in the My Relays tab. In addition, the active relays and observed bandwidth fields on the home page are perpetually loading. I can't include the full log because of the character limit of this field - I have therefore filtered for errors. Let me know if you'd like to see the full logs via email.

**Logs**

Thu, 19 Oct 2023 15:41:48 GMT | [ERROR][MetricsStore] Error querying relay/metrics TypeError: Failed to fetch at fetchCallImpl (https://gc.kis.v2.scr.kaspersky-labs.com/FD126C42-EBFA-4E12-B309-BB3FDD723AC1/main.js?attr=oIwceeOIHYBWGTM-z1nwVpaOo2L7y0Guk6UoONSgmlNQvBSUpUNGy3YKDmNAg5k8tE_Aud8Sg_qbBRsx1xg7hg:3452:21) at fetch (https://gc.kis.v2.scr.kaspersky-labs.com/FD126C42-EBFA-4E12-B309-BB3FDD723AC1/main.js?attr=oIwceeOIHYBWGTM-z1nwVpaOo2L7y0Guk6UoONSgmlNQvBSUpUNGy3YKDmNAg5k8tE_Aud8Sg_qbBRsx1xg7hg:3458:60) at Api.request (https://ator-dashboard.ar-io.dev/_nuxt/auth.36aa8730.js:6:120362) at Api.post (https://ator-dashboard.ar-io.dev/_nuxt/auth.36aa8730.js:6:119882) at ArDB.<anonymous> (https://ator-dashboard.ar-io.dev/_nuxt/auth.36aa8730.js:114:234618) at Generator.next (<anonymous>) at https://ator-dashboard.ar-io.dev/_nuxt/auth.36aa8730.js:114:228984 at new Promise (<anonymous>) at __awaiter (https://ator-dashboard.ar-io.dev/_nuxt/auth.36aa8730.js:114:228781) at ArDB.get (https://ator-dashboard.ar-io.dev/_nuxt/auth.36aa8730.js:114:234546)
-- | --
Thu, 19 Oct 2023 15:41:46 GMT | [ERROR][MetricsStore] Error querying validation/stats TypeError: Failed to fetch at fetchCallImpl (https://gc.kis.v2.scr.kaspersky-labs.com/FD126C42-EBFA-4E12-B309-BB3FDD723AC1/main.js?attr=oIwceeOIHYBWGTM-z1nwVpaOo2L7y0Guk6UoONSgmlNQvBSUpUNGy3YKDmNAg5k8tE_Aud8Sg_qbBRsx1xg7hg:3452:21) at fetch (https://gc.kis.v2.scr.kaspersky-labs.com/FD126C42-EBFA-4E12-B309-BB3FDD723AC1/main.js?attr=oIwceeOIHYBWGTM-z1nwVpaOo2L7y0Guk6UoONSgmlNQvBSUpUNGy3YKDmNAg5k8tE_Aud8Sg_qbBRsx1xg7hg:3458:60) at Api.request (https://ator-dashboard.ar-io.dev/_nuxt/auth.36aa8730.js:6:120362) at Api.post (https://ator-dashboard.ar-io.dev/_nuxt/auth.36aa8730.js:6:119882) at ArDB.<anonymous> (https://ator-dashboard.ar-io.dev/_nuxt/auth.36aa8730.js:114:234618) at Generator.next (<anonymous>) at https://ator-dashboard.ar-io.dev/_nuxt/auth.36aa8730.js:114:228984 at new Promise (<anonymous>) at __awaiter (https://ator-dashboard.ar-io.dev/_nuxt/auth.36aa8730.js:114:228781) at ArDB.get (https://ator-dashboard.ar-io.dev/_nuxt/auth.36aa8730.js:114:234546)
Thu, 19 Oct 2023 15:41:48 GMT | [ERROR][MetricsStore] Error querying relay/metrics TypeError: Failed to fetch at fetchCallImpl (https://gc.kis.v2.scr.kaspersky-labs.com/FD126C42-EBFA-4E12-B309-BB3FDD723AC1/main.js?attr=oIwceeOIHYBWGTM-z1nwVpaOo2L7y0Guk6UoONSgmlNQvBSUpUNGy3YKDmNAg5k8tE_Aud8Sg_qbBRsx1xg7hg:3452:21) at fetch (https://gc.kis.v2.scr.kaspersky-labs.com/FD126C42-EBFA-4E12-B309-BB3FDD723AC1/main.js?attr=oIwceeOIHYBWGTM-z1nwVpaOo2L7y0Guk6UoONSgmlNQvBSUpUNGy3YKDmNAg5k8tE_Aud8Sg_qbBRsx1xg7hg:3458:60) at Api.request (https://ator-dashboard.ar-io.dev/_nuxt/auth.36aa8730.js:6:120362) at Api.post (https://ator-dashboard.ar-io.dev/_nuxt/auth.36aa8730.js:6:119882) at ArDB.<anonymous> (https://ator-dashboard.ar-io.dev/_nuxt/auth.36aa8730.js:114:234618) at Generator.next (<anonymous>) at https://ator-dashboard.ar-io.dev/_nuxt/auth.36aa8730.js:114:228984 at new Promise (<anonymous>) at __awaiter (https://ator-dashboard.ar-io.dev/_nuxt/auth.36aa8730.js:114:228781) at ArDB.get (https://ator-dashboard.ar-io.dev/_nuxt/auth.36aa8730.js:114:234546)
Thu, 19 Oct 2023 15:42:09 GMT | [ERROR][useSigner] Error getting Signer Error: could not coalesce error (error={ "code": -32002, "payload": { "method": "eth_requestAccounts", "params": [ ] } }, payload={ "method": "eth_requestAccounts", "params": [ ] }, code=UNKNOWN_ERROR, version=6.7.1) at makeError (https://ator-dashboard.ar-io.dev/_nuxt/auth.36aa8730.js:1:2924) at BrowserProvider.getRpcError (https://ator-dashboard.ar-io.dev/_nuxt/auth.36aa8730.js:1:264162) at BrowserProvider.getRpcError (https://ator-dashboard.ar-io.dev/_nuxt/auth.36aa8730.js:1:298023) at BrowserProvider.getSigner (https://ator-dashboard.ar-io.dev/_nuxt/auth.36aa8730.js:1:298376) at async useSigner (https://ator-dashboard.ar-io.dev/_nuxt/auth.36aa8730.js:1:300339) at async connectAuth (https://ator-dashboard.ar-io.dev/_nuxt/auth.36aa8730.js:205:6106) at async https://ator-dashboard.ar-io.dev/_nuxt/ConnectButton.30384f87.js:1:1181

</body>
</html>

**Comment by jim-toth** [comment]
Hey, it looks like you've got some kind of virus scanner addon that is injecting javascript into the dashboard which results in these errors.

Since the dashboard is meant to be a standalone permaweb app with no external dependencies (other than decentralized data sources like arweave or ethereum), there's no code that should be requesting any resources from `kaspersky-labs.com`.  So, it seems a browser plugin you are using is preventing the dashboard from working.

Please try disabling any virus scanner related browser plugins and see if you're still getting an issue.

**Comment by ercbul** [comment]
I have disabled the Kaspersky Chrome extension but the same behaviour persists. Quite a few folk on discord and telegram complaining of the same thing. Rewards still accruing and claimable but no relays are visible.
