### ISSUE TITLE
RELAYS IS NOT SHOW MY RELAY

### ISSUE THREAD

**Issue by lyhaidang1783** [ATOR-Development/ator-dashboard#124]
**Description**
Dear Team,
Good day to you
I have run a Relay base on the Video youtube but  in this platform does not show my relay pls check info as below
Finger: CCDE2802C10A3EAF8940A045B26158FB33E693F9
my wallet contract: 0x370dbe54452b76f3c9d78d9a8bcde75c1ed3e5cf

**Logs**
<Paste Encrypted Logs Here>

**Comment by 0xneuratic** [comment]
Hi there, according to the Tor relay search feature [here](https://metrics.torproject.org/rs.html#search) and other cached stores of metrics, your relay fingerprint isn't present. It seems this an issue with your relay and not the platform. You can go to the ATOR [Discord](https://discord.gg/ator) and try and get some help.
