### ISSUE TITLE
Unable to claim pending rewards

### ISSUE THREAD

**Issue by misel86** [ATOR-Development/ator-dashboard#98]
Hello,

for a while now my dashboard is stuck on the following screen:

![image](https://github.com/ATOR-Development/ator-dashboard/assets/5527854/a54a2094-8273-4dfd-b0a2-b51171fb4b1f)

I get the same behaviour if I clear cache, even in incognito. Looks like the process did not finish after my last claim.

**Comment by kanshi** [comment]
Hi, please provide the test account's address so we can review.

**Comment by misel86** [comment]
Hello, it is 0xacF8A386FD79f71379759515024Bd2ce3072B30b
_____________
*Üdvözlettel,*

*Juhász Misel*

**Comment by misel86** [comment]
Hello, I still (once again) have the same issue:

![2023-10-07 00_00_32-Window](https://github.com/ATOR-Development/ator-dashboard/assets/5527854/cbd0f292-9bd8-4fba-a689-a7cc326ccb91)
